blank_issues_enabled: false
contact_links:
  - name: ğŸ’¡ Have an idea for a new feature?
    url: https://github.com/gtronset/beets-filetote/discussions/categories/ideas
    about: Create a new idea discussion!
  - name: ğŸ™‡ Need help with Filetote?
    url: https://github.com/gtronset/beets-filetote/discussions/categories/general
    about: Create a new help discussion if it hasn't been asked before!
